services:
  - type: web
    name: masesora-backend
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r masesora_backend/requirements.txt
    startCommand: sh -c "cd masesora_backend && exec uvicorn main:app --host 0.0.0.0 --port $PORT"
    pythonVersion: 3.10
